<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>BoomifyCS</AssemblyTitle>
    <Product>BoomifyCS</Product>
    <Copyright>Copyright ©  2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);DEBUG_COMPILE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Content Include=".gitignore" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="libLLVM" Version="23.1.0" />
    <PackageReference Include="libLLVM.runtime.linux-x64" Version="23.1.0" />
    <PackageReference Include="LLVMSharp" Version="20.1.2" />
    <PackageReference Include="LLVMSharp.Interop" Version="20.1.2" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Nunit" Version="4.1.0" />
    <PackageReference Include="System.CommandLine" Version="3.0.0-preview.7.26381.103" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Colorful.Console" Version="1.2.15" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Traceback\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\Debug\libLLVM.dll" />
    <None Include="bin\Debug\net8.0\libLLVM.dll" />
  </ItemGroup>
</Project>